apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonrisas
resources:
  - app-config.yaml
  - migrate-job.yaml
  - web.yaml
  - workers.yaml
  - certificate.yaml
  - ingress.yaml