apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonrisas
resources:
  - ../../base

# Release tag de prod. Subir acá cuando se publique una nueva versión.
# Requiere que el CI de sonrisasuy publique ghcr.io/.../sonrisas-{web,worker}:1.0.0
images:
  - name: ghcr.io/calabri1/sonrisas-web
    newTag: "v0.0.2"
  - name: ghcr.io/calabri1/sonrisas-worker
    newTag: "v0.0.2"
