apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonrisas
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ManuelGorospe/sonrisasuy.git
    targetRevision: main
    path: infra/deploy/k3s/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sonrisas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
