apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sonrisas
resources:
  - ../../base
# Patch backup block here when Garage is operational.
# patches:
#   - path: patch-backup.yaml
